---

- hosts: app_server
  remote_user: root
  become: yes
  become_method: sudo
  vars:
      artifactory_url: http://13.250.106.96:8081/artifactory/WebappJava/
      application_artifact: StrutsLoginEx.war
      source_path: /opt/artifactory_packages/
      dest_path: /usr/share/tomcat7/webapps/
      http_port: 8080
      https_port: 8443
  tasks:
      - name: create artifactory folder
        file:
           path: /opt/artifactory_packages
           state: directory
           recurse: yes
      - name: download artifact from artifary
        get_url:
          url: "{{ artifactory_url }}{{ application_artifact}}"
          dest: "{{ source_path }}"
      - name: copy file to tomcat folder
        copy:
          src: "{{ source_path }}{{ application_artifact }}"
          dest: "{{ dest_path }}{{ application_artifact }}"
          owner: tomcat
          group: tomcat
          mode: 0755
      - name: Restart Tomcat
        service: name=tomcat state=started enabled=yes
      - name: wait for tomcat to start
        wait_for: port={{http_port}}